### PR TITLE
Add-on configuration compatibility with Supervisor 2021.2

### LINKED ISSUE #8: Deprecated format after upgrade to supervisor 2021.02.5
After updating the HA Supervisor (from 2021.01.7 to 2021.02.5), I get the following warnings in the supervisor logging.
Can you please have a look at this?
(hope to have reported this in the correct repository)

WARNING (MainThread) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of DOODS-amd64
WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of DOODS-amd64
WARNING (MainThread) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of DOODS-cuda
WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of DOODS-cuda
WARNING (MainThread) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of DOODS
WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of DOODS

### PR DESCRIPTION
**Pull request by frenck**
Updates add-on configurations in this repository. Cleaned them up and made them compatible with the latest supervisor.

Additionally, added a GitHub Actions that checks the configuration and configured dependabot to keep the GitHub Actions up2date.

fixed #8

### CODE REVIEW

**Comment by frenck** [comment]
The run of the GitHub Action can be seen here: <https://github.com/frenck/hassio-addons-1/actions/runs/548749910>

**Comment by snowzach** [comment]
This looks pretty awesome @frenck I honestly don't have time to validate it all... I assume you tested it?

**Comment by frenck** [comment]
No, I have not. This is based on experience + the added add-on linter that validates.

**Comment by frenck** [comment]
LOL OK and merged. I have the repo installed on my main instance, will go and ensure its working right away 👍

**Comment by snowzach** [comment]
I've seen your work before... I would appreciate it if you have time to validate it if you did... I'll point people to you if it breaks. :-P

**Comment by frenck** [comment]
@snowzach Works 👍 
And all warnings are gone 🎉

**Pull request merged**
